from gym_minigrid.wrappers import FullyObsWrapper
from gym_minigrid.wrappers import FlatObsWrapper
import matplotlib.pyplot as plt
import numpy as np
import gym
from gym.wrappers import Monitor
import os
from env_transfer.DoorGoal import SimpleDoorGoalEnv
from env_transfer.BoxDoor import BoxDoorEnv
from env_transfer.BlockedDoor import BlockedDoorEnv
from env_transfer.BallKey import SimpleBallKeyEnv
from env_transfer.GapBall import SimpleGapBallEnv
from env_transfer.BlockedBoxUnlockPickup import BlockedBoxUnlockPickupEnv
from env_transfer.BlockedBoxPlaceGoal import BlockedBoxPlaceGoalEnv
from PIL import Image

path = './env_2'
np.random.seed(23)
if not os.path.exists(path):
    os.makedirs(os.path.join(path))
# env = Monitor(FullyObsWrapper(BlockedBoxUnlockPickupEnv()), './video', force=True)
env = FullyObsWrapper(BlockedBoxUnlockPickupEnv())
env.reset()
img = env.render('rgb')
# img = img[:, 225:, :]
# print(img, img.shape)
img = Image.fromarray(img)
plt.imshow(img)
# img.save(path + '/0.jpg')
plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/1.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/2.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/3.jpg')
# plt.show()
# env.step(0)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/4.jpg')
# plt.show()
# env.step(3)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/5.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/6.jpg')
# plt.show()
# env.step(0)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/7.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/8.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/9.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/10.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/11.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/12.jpg')
# plt.show()
# env.step(1)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/13.jpg')
# plt.show()
# env.step(5)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/14.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/15.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/16.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/17.jpg')
# plt.show()
# env.step(1)
# img = env.render('rgb')
# # img = img[:, 225:, :]
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/18.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/19.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/20.jpg')
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/21.jpg')
# plt.show()
# env.step(0)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/22.jpg')
# plt.show()
# env.step(4)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/23.jpg')
# plt.show()
# env.step(1)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/24.jpg')
# plt.show()
# env.step(3)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/25.jpg')
# plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/26.jpg')
# # plt.show()
# # env.step(1)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/27.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/28.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/29.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/30.jpg')
# # plt.show()
# # env.step(0)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/31.jpg')
# # plt.show()
# # env.step(5)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/32.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/33.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/34.jpg')
# # plt.show()
# #
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/35.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/36.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/37.jpg')
# # plt.show()
# # env.step(2)
# # img = env.render('rgb')
# # plt.imshow(img)
# # img = Image.fromarray(img)
# # img.save(path + '/38.jpg')
# # plt.show()
# # env.step(0)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/39.jpg')
# plt.show()
# env.step(1)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/40.jpg')
# plt.show()
# env.step(4)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/41.jpg')
# plt.show()
# env.step(0)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/42.jpg')
# plt.show()
# env.step(3)
# img = env.render('rgb')
# plt.imshow(img)
# img = Image.fromarray(img)
# img.save(path + '/43.jpg')
# plt.show()
# env.step(1)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(1)
# env.step(3)
# env.step(2)
# env.step(1)
# env.step(4)

# print(env.pos_goal)
# def trans_square(img):
#     img_h, img_w, img_c = img.shape
#     if img_h != img_w:
#         long_side = max(img_w, img_h)
#         short_side = min(img_w, img_h)
#         loc = abs(img_w - img_h) // 2
#         img = img.transpose((1, 0, 2)) if img_w < img_h else img  # 如果高是长边则换轴，最后再换回来
#         background = np.zeros((long_side, long_side, img_c), dtype=np.uint8)  # 创建正方形背景
#         background[loc: loc + short_side] = img[...]  # 数据填充在中间位置
#         img = background.transpose((1, 0, 2)) if img_w < img_h else background
#     return img
#
# print(img)
# img = trans_square(img)
# # img = img.resize((224, 224), Image.ANTIALIAS)
# # img = img.resize((224., 224.), Image.ANTIALIAS)
# print(img, img.shape)
# im = Image.fromarray(img)
# im.save('5.jpg')

# env.step(0)
# env.step(2)
# env.step(3)
# env.step(0)
# env.step(2)
# env.step(0)
# env.step(2)
# env.step(4)
# env.step(0)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(1)
# env.step(2)
# env.step(5)
# env.step(3)
# env.step(1)
# env.step(2)
# env.step(2)
# env.step(1)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(5)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(0)
# env.step(2)
# env.step(2)
# env.step(1)
# env.step(4)
# env.step(0)
# env.step(3)
# env.step(2)
# env.step(0)
# #
# s ,r,done,_ = env.step(4)
# print("-"*100)
# print(s, r, done)
# print(s['image'])
# env.step(2)
# env.step(0)
# env.step(0)
# env.step(4)
# env.step(1)
# env.step(5)
# env.step(3)
# env.step(1)
# env.step(1)
# env.step(2)
# env.step(1)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(0)
# env.step(5)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(2)
# env.step(0)
# env.step(4)
# env.step(1)
# _,re,done,_=env.step(3)
# # print(re, done)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()

# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()

# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# s = env.reset()
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# s = s['image']
# print(s)
# agent_pos = np.array(np.where(s==8))[:2].reshape(-1).tolist()
# print(agent_pos)
# agent_surrounding_pos = [[agent_pos[0]-1, agent_pos[1]],
#                         [agent_pos[0]+1, agent_pos[1]],
#                          [agent_pos[0], agent_pos[1]-1],
#                          [agent_pos[0], agent_pos[1]+1]]
# for index, value in enumerate(agent_surrounding_pos):
#     print(s[value[0]][value[1]][0])
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
#
# env.step(1)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(0)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(5)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(2)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
#
# env.step(1)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(4)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# env.step(0)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# _,_,done,_=env.step(3)
# img = env.render('rgb')
# plt.imshow(img) # 显示图片
# plt.show()
# print(done)